### ISSUE TITLE
Unrecognized archive format

### ISSUE THREAD

**Issue by svanharmelen** [tree-sitter-grammars/tree-sitter-smali#1]
When trying to use (install) the grammar using Packer (in neovim), I get this error:

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/4171547/220572860-65aa22c3-4a83-42ac-92d7-472ac6b98dc0.png">

I've installed the grammar before, so my guess is that it related to the latest changes somehow?

**Comment by ToyVo** [comment]
I also have error when using nix & home-manager
```
trying https://github.com/amaanq/tree-sitter-smali/archive/d7f535e176c928d33b0e202dd808ac247cacf2ff.tar.gz
curl: (22) The requested URL returned error: 404
error: cannot download source from any mirror
```
I don't know if there was a force push or something I don't see that hash in a quick search through the commits

**Comment by amaanq** [comment]
@yotamN (the original author) expressed interest in collaborating in this with me. That source lives at https://git.sr.ht/~yotam/tree-sitter-smali. I deleted the repo in an attempt to purely mirror that (mainly wanted it to say mirror of https://git.sr.ht/~yotam/tree-sitter-smali at the top left corner below my repo name). After doing that, I realized there was no change at all, and the ci actions weren't running anymore as well. So I deleted it again and just kept it as it was before.

If you use nvim-treesitter, update your package to include this [PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/4351).

If you used my old repo, delete and reinstall it thru whatever method you used before (@ToyVo, is this on nixpkgs? please update it if so)

**Comment by ToyVo** [comment]
Yes on nixpkgs, I'm working on creating a pr

**Comment by amaanq** [comment]
Thanks! Sorry about that

But hopefully I made it up by completing the grammar fully :)
